// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/connection.dart';
import 'api/query.dart';
import 'api/simple.dart';
import 'api/table.dart';
import 'api/types.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -1915519320;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'flutter_lancedb',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<LanceTable> crateApiConnectionLanceConnectionCreateEmptyTable({
    required LanceConnection that,
    required String name,
    required String schemaJson,
  });

  Future<LanceTable> crateApiConnectionLanceConnectionCreateTable({
    required LanceConnection that,
    required String name,
    required String dataJson,
  });

  Future<void> crateApiConnectionLanceConnectionDropTable({
    required LanceConnection that,
    required String name,
  });

  Future<LanceTable> crateApiConnectionLanceConnectionOpenTable({
    required LanceConnection that,
    required String name,
  });

  Future<List<String>> crateApiConnectionLanceConnectionTableNames({
    required LanceConnection that,
  });

  Future<void> crateApiTableLanceTableAdd({
    required LanceTable that,
    required String dataJson,
  });

  Future<PlatformInt64> crateApiTableLanceTableCountRows({
    required LanceTable that,
    String? filter,
  });

  Future<void> crateApiTableLanceTableCreateIndex({
    required LanceTable that,
    required String column,
    String? indexType,
    bool? replace,
  });

  Future<void> crateApiTableLanceTableDelete({
    required LanceTable that,
    required String predicate,
  });

  Future<List<String>> crateApiTableLanceTableListIndices({
    required LanceTable that,
  });

  String crateApiTableLanceTableName({required LanceTable that});

  Future<String> crateApiTableLanceTableOptimize({required LanceTable that});

  Future<QueryResult> crateApiTableLanceTableQuery({
    required LanceTable that,
    List<String>? columns,
    String? filter,
    PlatformInt64? limit,
  });

  Future<SchemaInfo> crateApiTableLanceTableSchema({required LanceTable that});

  Future<PlatformInt64> crateApiTableLanceTableUpdate({
    required LanceTable that,
    required String updatesJson,
    String? predicate,
  });

  Future<LanceVectorQuery> crateApiTableLanceTableVectorSearch({
    required LanceTable that,
    required List<double> vector,
    String? column,
  });

  Future<PlatformInt64> crateApiTableLanceTableVersion({
    required LanceTable that,
  });

  LanceVectorQuery crateApiQueryLanceVectorQueryColumn({
    required LanceVectorQuery that,
    required String column,
  });

  LanceVectorQuery crateApiQueryLanceVectorQueryDistanceType({
    required LanceVectorQuery that,
    required DistanceType distanceType,
  });

  Future<QueryResult> crateApiQueryLanceVectorQueryExecute({
    required LanceVectorQuery that,
  });

  LanceVectorQuery crateApiQueryLanceVectorQueryLimit({
    required LanceVectorQuery that,
    required PlatformInt64 limit,
  });

  LanceVectorQuery crateApiQueryLanceVectorQueryNprobes({
    required LanceVectorQuery that,
    required int nprobes,
  });

  LanceVectorQuery crateApiQueryLanceVectorQueryOffset({
    required LanceVectorQuery that,
    required PlatformInt64 offset,
  });

  LanceVectorQuery crateApiQueryLanceVectorQueryOnlyIf({
    required LanceVectorQuery that,
    required String predicate,
  });

  LanceVectorQuery crateApiQueryLanceVectorQueryPostfilter({
    required LanceVectorQuery that,
  });

  LanceVectorQuery crateApiQueryLanceVectorQueryRefineFactor({
    required LanceVectorQuery that,
    required int factor,
  });

  LanceVectorQuery crateApiQueryLanceVectorQuerySelect({
    required LanceVectorQuery that,
    required List<String> columns,
  });

  Future<LanceConnection> crateApiConnectionConnect({required String uri});

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  Future<QueryResult> crateApiTypesQueryResultEmpty();

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_LanceConnection;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_LanceConnection;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_LanceConnectionPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_LanceTable;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_LanceTable;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_LanceTablePtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_LanceVectorQuery;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_LanceVectorQuery;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_LanceVectorQueryPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<LanceTable> crateApiConnectionLanceConnectionCreateEmptyTable({
    required LanceConnection that,
    required String name,
    required String schemaJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceConnection(
            that,
            serializer,
          );
          sse_encode_String(name, serializer);
          sse_encode_String(schemaJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceTable,
          decodeErrorData: sse_decode_lance_error,
        ),
        constMeta: kCrateApiConnectionLanceConnectionCreateEmptyTableConstMeta,
        argValues: [that, name, schemaJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiConnectionLanceConnectionCreateEmptyTableConstMeta =>
      const TaskConstMeta(
        debugName: "LanceConnection_create_empty_table",
        argNames: ["that", "name", "schemaJson"],
      );

  @override
  Future<LanceTable> crateApiConnectionLanceConnectionCreateTable({
    required LanceConnection that,
    required String name,
    required String dataJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceConnection(
            that,
            serializer,
          );
          sse_encode_String(name, serializer);
          sse_encode_String(dataJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceTable,
          decodeErrorData: sse_decode_lance_error,
        ),
        constMeta: kCrateApiConnectionLanceConnectionCreateTableConstMeta,
        argValues: [that, name, dataJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConnectionLanceConnectionCreateTableConstMeta =>
      const TaskConstMeta(
        debugName: "LanceConnection_create_table",
        argNames: ["that", "name", "dataJson"],
      );

  @override
  Future<void> crateApiConnectionLanceConnectionDropTable({
    required LanceConnection that,
    required String name,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceConnection(
            that,
            serializer,
          );
          sse_encode_String(name, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_lance_error,
        ),
        constMeta: kCrateApiConnectionLanceConnectionDropTableConstMeta,
        argValues: [that, name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConnectionLanceConnectionDropTableConstMeta =>
      const TaskConstMeta(
        debugName: "LanceConnection_drop_table",
        argNames: ["that", "name"],
      );

  @override
  Future<LanceTable> crateApiConnectionLanceConnectionOpenTable({
    required LanceConnection that,
    required String name,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceConnection(
            that,
            serializer,
          );
          sse_encode_String(name, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceTable,
          decodeErrorData: sse_decode_lance_error,
        ),
        constMeta: kCrateApiConnectionLanceConnectionOpenTableConstMeta,
        argValues: [that, name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConnectionLanceConnectionOpenTableConstMeta =>
      const TaskConstMeta(
        debugName: "LanceConnection_open_table",
        argNames: ["that", "name"],
      );

  @override
  Future<List<String>> crateApiConnectionLanceConnectionTableNames({
    required LanceConnection that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceConnection(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_lance_error,
        ),
        constMeta: kCrateApiConnectionLanceConnectionTableNamesConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConnectionLanceConnectionTableNamesConstMeta =>
      const TaskConstMeta(
        debugName: "LanceConnection_table_names",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiTableLanceTableAdd({
    required LanceTable that,
    required String dataJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceTable(
            that,
            serializer,
          );
          sse_encode_String(dataJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_lance_error,
        ),
        constMeta: kCrateApiTableLanceTableAddConstMeta,
        argValues: [that, dataJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTableLanceTableAddConstMeta => const TaskConstMeta(
    debugName: "LanceTable_add",
    argNames: ["that", "dataJson"],
  );

  @override
  Future<PlatformInt64> crateApiTableLanceTableCountRows({
    required LanceTable that,
    String? filter,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceTable(
            that,
            serializer,
          );
          sse_encode_opt_String(filter, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: sse_decode_lance_error,
        ),
        constMeta: kCrateApiTableLanceTableCountRowsConstMeta,
        argValues: [that, filter],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTableLanceTableCountRowsConstMeta =>
      const TaskConstMeta(
        debugName: "LanceTable_count_rows",
        argNames: ["that", "filter"],
      );

  @override
  Future<void> crateApiTableLanceTableCreateIndex({
    required LanceTable that,
    required String column,
    String? indexType,
    bool? replace,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceTable(
            that,
            serializer,
          );
          sse_encode_String(column, serializer);
          sse_encode_opt_String(indexType, serializer);
          sse_encode_opt_box_autoadd_bool(replace, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_lance_error,
        ),
        constMeta: kCrateApiTableLanceTableCreateIndexConstMeta,
        argValues: [that, column, indexType, replace],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTableLanceTableCreateIndexConstMeta =>
      const TaskConstMeta(
        debugName: "LanceTable_create_index",
        argNames: ["that", "column", "indexType", "replace"],
      );

  @override
  Future<void> crateApiTableLanceTableDelete({
    required LanceTable that,
    required String predicate,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceTable(
            that,
            serializer,
          );
          sse_encode_String(predicate, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_lance_error,
        ),
        constMeta: kCrateApiTableLanceTableDeleteConstMeta,
        argValues: [that, predicate],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTableLanceTableDeleteConstMeta =>
      const TaskConstMeta(
        debugName: "LanceTable_delete",
        argNames: ["that", "predicate"],
      );

  @override
  Future<List<String>> crateApiTableLanceTableListIndices({
    required LanceTable that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceTable(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_lance_error,
        ),
        constMeta: kCrateApiTableLanceTableListIndicesConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTableLanceTableListIndicesConstMeta =>
      const TaskConstMeta(
        debugName: "LanceTable_list_indices",
        argNames: ["that"],
      );

  @override
  String crateApiTableLanceTableName({required LanceTable that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceTable(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTableLanceTableNameConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTableLanceTableNameConstMeta =>
      const TaskConstMeta(debugName: "LanceTable_name", argNames: ["that"]);

  @override
  Future<String> crateApiTableLanceTableOptimize({required LanceTable that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceTable(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_lance_error,
        ),
        constMeta: kCrateApiTableLanceTableOptimizeConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTableLanceTableOptimizeConstMeta =>
      const TaskConstMeta(debugName: "LanceTable_optimize", argNames: ["that"]);

  @override
  Future<QueryResult> crateApiTableLanceTableQuery({
    required LanceTable that,
    List<String>? columns,
    String? filter,
    PlatformInt64? limit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceTable(
            that,
            serializer,
          );
          sse_encode_opt_list_String(columns, serializer);
          sse_encode_opt_String(filter, serializer);
          sse_encode_opt_box_autoadd_i_64(limit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_query_result,
          decodeErrorData: sse_decode_lance_error,
        ),
        constMeta: kCrateApiTableLanceTableQueryConstMeta,
        argValues: [that, columns, filter, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTableLanceTableQueryConstMeta =>
      const TaskConstMeta(
        debugName: "LanceTable_query",
        argNames: ["that", "columns", "filter", "limit"],
      );

  @override
  Future<SchemaInfo> crateApiTableLanceTableSchema({required LanceTable that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceTable(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_schema_info,
          decodeErrorData: sse_decode_lance_error,
        ),
        constMeta: kCrateApiTableLanceTableSchemaConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTableLanceTableSchemaConstMeta =>
      const TaskConstMeta(debugName: "LanceTable_schema", argNames: ["that"]);

  @override
  Future<PlatformInt64> crateApiTableLanceTableUpdate({
    required LanceTable that,
    required String updatesJson,
    String? predicate,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceTable(
            that,
            serializer,
          );
          sse_encode_String(updatesJson, serializer);
          sse_encode_opt_String(predicate, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: sse_decode_lance_error,
        ),
        constMeta: kCrateApiTableLanceTableUpdateConstMeta,
        argValues: [that, updatesJson, predicate],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTableLanceTableUpdateConstMeta =>
      const TaskConstMeta(
        debugName: "LanceTable_update",
        argNames: ["that", "updatesJson", "predicate"],
      );

  @override
  Future<LanceVectorQuery> crateApiTableLanceTableVectorSearch({
    required LanceTable that,
    required List<double> vector,
    String? column,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceTable(
            that,
            serializer,
          );
          sse_encode_list_prim_f_32_loose(vector, serializer);
          sse_encode_opt_String(column, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceVectorQuery,
          decodeErrorData: sse_decode_lance_error,
        ),
        constMeta: kCrateApiTableLanceTableVectorSearchConstMeta,
        argValues: [that, vector, column],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTableLanceTableVectorSearchConstMeta =>
      const TaskConstMeta(
        debugName: "LanceTable_vector_search",
        argNames: ["that", "vector", "column"],
      );

  @override
  Future<PlatformInt64> crateApiTableLanceTableVersion({
    required LanceTable that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceTable(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: sse_decode_lance_error,
        ),
        constMeta: kCrateApiTableLanceTableVersionConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTableLanceTableVersionConstMeta =>
      const TaskConstMeta(debugName: "LanceTable_version", argNames: ["that"]);

  @override
  LanceVectorQuery crateApiQueryLanceVectorQueryColumn({
    required LanceVectorQuery that,
    required String column,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceVectorQuery(
            that,
            serializer,
          );
          sse_encode_String(column, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceVectorQuery,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiQueryLanceVectorQueryColumnConstMeta,
        argValues: [that, column],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiQueryLanceVectorQueryColumnConstMeta =>
      const TaskConstMeta(
        debugName: "LanceVectorQuery_column",
        argNames: ["that", "column"],
      );

  @override
  LanceVectorQuery crateApiQueryLanceVectorQueryDistanceType({
    required LanceVectorQuery that,
    required DistanceType distanceType,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceVectorQuery(
            that,
            serializer,
          );
          sse_encode_distance_type(distanceType, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceVectorQuery,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiQueryLanceVectorQueryDistanceTypeConstMeta,
        argValues: [that, distanceType],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiQueryLanceVectorQueryDistanceTypeConstMeta =>
      const TaskConstMeta(
        debugName: "LanceVectorQuery_distance_type",
        argNames: ["that", "distanceType"],
      );

  @override
  Future<QueryResult> crateApiQueryLanceVectorQueryExecute({
    required LanceVectorQuery that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceVectorQuery(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_query_result,
          decodeErrorData: sse_decode_lance_error,
        ),
        constMeta: kCrateApiQueryLanceVectorQueryExecuteConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiQueryLanceVectorQueryExecuteConstMeta =>
      const TaskConstMeta(
        debugName: "LanceVectorQuery_execute",
        argNames: ["that"],
      );

  @override
  LanceVectorQuery crateApiQueryLanceVectorQueryLimit({
    required LanceVectorQuery that,
    required PlatformInt64 limit,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceVectorQuery(
            that,
            serializer,
          );
          sse_encode_i_64(limit, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceVectorQuery,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiQueryLanceVectorQueryLimitConstMeta,
        argValues: [that, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiQueryLanceVectorQueryLimitConstMeta =>
      const TaskConstMeta(
        debugName: "LanceVectorQuery_limit",
        argNames: ["that", "limit"],
      );

  @override
  LanceVectorQuery crateApiQueryLanceVectorQueryNprobes({
    required LanceVectorQuery that,
    required int nprobes,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceVectorQuery(
            that,
            serializer,
          );
          sse_encode_i_32(nprobes, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceVectorQuery,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiQueryLanceVectorQueryNprobesConstMeta,
        argValues: [that, nprobes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiQueryLanceVectorQueryNprobesConstMeta =>
      const TaskConstMeta(
        debugName: "LanceVectorQuery_nprobes",
        argNames: ["that", "nprobes"],
      );

  @override
  LanceVectorQuery crateApiQueryLanceVectorQueryOffset({
    required LanceVectorQuery that,
    required PlatformInt64 offset,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceVectorQuery(
            that,
            serializer,
          );
          sse_encode_i_64(offset, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 23)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceVectorQuery,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiQueryLanceVectorQueryOffsetConstMeta,
        argValues: [that, offset],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiQueryLanceVectorQueryOffsetConstMeta =>
      const TaskConstMeta(
        debugName: "LanceVectorQuery_offset",
        argNames: ["that", "offset"],
      );

  @override
  LanceVectorQuery crateApiQueryLanceVectorQueryOnlyIf({
    required LanceVectorQuery that,
    required String predicate,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceVectorQuery(
            that,
            serializer,
          );
          sse_encode_String(predicate, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 24)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceVectorQuery,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiQueryLanceVectorQueryOnlyIfConstMeta,
        argValues: [that, predicate],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiQueryLanceVectorQueryOnlyIfConstMeta =>
      const TaskConstMeta(
        debugName: "LanceVectorQuery_only_if",
        argNames: ["that", "predicate"],
      );

  @override
  LanceVectorQuery crateApiQueryLanceVectorQueryPostfilter({
    required LanceVectorQuery that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceVectorQuery(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 25)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceVectorQuery,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiQueryLanceVectorQueryPostfilterConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiQueryLanceVectorQueryPostfilterConstMeta =>
      const TaskConstMeta(
        debugName: "LanceVectorQuery_postfilter",
        argNames: ["that"],
      );

  @override
  LanceVectorQuery crateApiQueryLanceVectorQueryRefineFactor({
    required LanceVectorQuery that,
    required int factor,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceVectorQuery(
            that,
            serializer,
          );
          sse_encode_i_32(factor, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 26)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceVectorQuery,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiQueryLanceVectorQueryRefineFactorConstMeta,
        argValues: [that, factor],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiQueryLanceVectorQueryRefineFactorConstMeta =>
      const TaskConstMeta(
        debugName: "LanceVectorQuery_refine_factor",
        argNames: ["that", "factor"],
      );

  @override
  LanceVectorQuery crateApiQueryLanceVectorQuerySelect({
    required LanceVectorQuery that,
    required List<String> columns,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceVectorQuery(
            that,
            serializer,
          );
          sse_encode_list_String(columns, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 27)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceVectorQuery,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiQueryLanceVectorQuerySelectConstMeta,
        argValues: [that, columns],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiQueryLanceVectorQuerySelectConstMeta =>
      const TaskConstMeta(
        debugName: "LanceVectorQuery_select",
        argNames: ["that", "columns"],
      );

  @override
  Future<LanceConnection> crateApiConnectionConnect({required String uri}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(uri, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceConnection,
          decodeErrorData: sse_decode_lance_error,
        ),
        constMeta: kCrateApiConnectionConnectConstMeta,
        argValues: [uri],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConnectionConnectConstMeta =>
      const TaskConstMeta(debugName: "connect", argNames: ["uri"]);

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 29)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 30,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<QueryResult> crateApiTypesQueryResultEmpty() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 31,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_query_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTypesQueryResultEmptyConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTypesQueryResultEmptyConstMeta =>
      const TaskConstMeta(debugName: "query_result_empty", argNames: []);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_LanceConnection => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceConnection;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_LanceConnection => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceConnection;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_LanceTable => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceTable;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_LanceTable => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceTable;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_LanceVectorQuery => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceVectorQuery;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_LanceVectorQuery => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceVectorQuery;

  @protected
  LanceConnection
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceConnection(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LanceConnectionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  LanceTable
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceTable(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LanceTableImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  LanceVectorQuery
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceVectorQuery(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LanceVectorQueryImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  LanceConnection
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceConnection(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LanceConnectionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  LanceTable
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceTable(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LanceTableImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  LanceVectorQuery
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceVectorQuery(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LanceVectorQueryImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Map<String, ColumnValue> dco_decode_Map_String_column_value_None(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Map.fromEntries(
      dco_decode_list_record_string_column_value(
        raw,
      ).map((e) => MapEntry(e.$1, e.$2)),
    );
  }

  @protected
  LanceConnection
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceConnection(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LanceConnectionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  LanceTable
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceTable(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LanceTableImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  LanceVectorQuery
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceVectorQuery(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LanceVectorQueryImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  ColumnValue dco_decode_column_value(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return ColumnValue_Null();
      case 1:
        return ColumnValue_Bool(dco_decode_bool(raw[1]));
      case 2:
        return ColumnValue_Int(dco_decode_i_64(raw[1]));
      case 3:
        return ColumnValue_Float(dco_decode_f_64(raw[1]));
      case 4:
        return ColumnValue_String(dco_decode_String(raw[1]));
      case 5:
        return ColumnValue_FloatArray(dco_decode_list_prim_f_64_strict(raw[1]));
      case 6:
        return ColumnValue_IntArray(dco_decode_list_prim_i_64_strict(raw[1]));
      case 7:
        return ColumnValue_StringArray(dco_decode_list_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  DistanceType dco_decode_distance_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return DistanceType.values[raw as int];
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  FieldInfo dco_decode_field_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return FieldInfo(
      name: dco_decode_String(arr[0]),
      dataType: dco_decode_String(arr[1]),
      nullable: dco_decode_bool(arr[2]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  LanceError dco_decode_lance_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return LanceError(
      message: dco_decode_String(arr[0]),
      code: dco_decode_String(arr[1]),
    );
  }

  @protected
  List<Map<String, ColumnValue>> dco_decode_list_Map_String_column_value_None(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_Map_String_column_value_None)
        .toList();
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<FieldInfo> dco_decode_list_field_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_field_info).toList();
  }

  @protected
  List<double> dco_decode_list_prim_f_32_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<double>;
  }

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float32List;
  }

  @protected
  Float64List dco_decode_list_prim_f_64_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float64List;
  }

  @protected
  Int64List dco_decode_list_prim_i_64_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeInt64List(raw);
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<(String, ColumnValue)> dco_decode_list_record_string_column_value(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_record_string_column_value)
        .toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_bool(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_String(raw);
  }

  @protected
  QueryResult dco_decode_query_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return QueryResult(
      columns: dco_decode_list_String(arr[0]),
      rows: dco_decode_list_Map_String_column_value_None(arr[1]),
      numRows: dco_decode_usize(arr[2]),
    );
  }

  @protected
  (String, ColumnValue) dco_decode_record_string_column_value(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_String(arr[0]), dco_decode_column_value(arr[1]));
  }

  @protected
  SchemaInfo dco_decode_schema_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return SchemaInfo(fields: dco_decode_list_field_info(arr[0]));
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  LanceConnection
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceConnection(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return LanceConnectionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  LanceTable
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceTable(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return LanceTableImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  LanceVectorQuery
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceVectorQuery(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return LanceVectorQueryImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  LanceConnection
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceConnection(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return LanceConnectionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  LanceTable
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceTable(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return LanceTableImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  LanceVectorQuery
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceVectorQuery(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return LanceVectorQueryImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Map<String, ColumnValue> sse_decode_Map_String_column_value_None(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_record_string_column_value(deserializer);
    return Map.fromEntries(inner.map((e) => MapEntry(e.$1, e.$2)));
  }

  @protected
  LanceConnection
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceConnection(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return LanceConnectionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  LanceTable
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceTable(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return LanceTableImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  LanceVectorQuery
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceVectorQuery(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return LanceVectorQueryImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_bool(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  ColumnValue sse_decode_column_value(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return ColumnValue_Null();
      case 1:
        var var_field0 = sse_decode_bool(deserializer);
        return ColumnValue_Bool(var_field0);
      case 2:
        var var_field0 = sse_decode_i_64(deserializer);
        return ColumnValue_Int(var_field0);
      case 3:
        var var_field0 = sse_decode_f_64(deserializer);
        return ColumnValue_Float(var_field0);
      case 4:
        var var_field0 = sse_decode_String(deserializer);
        return ColumnValue_String(var_field0);
      case 5:
        var var_field0 = sse_decode_list_prim_f_64_strict(deserializer);
        return ColumnValue_FloatArray(var_field0);
      case 6:
        var var_field0 = sse_decode_list_prim_i_64_strict(deserializer);
        return ColumnValue_IntArray(var_field0);
      case 7:
        var var_field0 = sse_decode_list_String(deserializer);
        return ColumnValue_StringArray(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  DistanceType sse_decode_distance_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return DistanceType.values[inner];
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  FieldInfo sse_decode_field_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_dataType = sse_decode_String(deserializer);
    var var_nullable = sse_decode_bool(deserializer);
    return FieldInfo(
      name: var_name,
      dataType: var_dataType,
      nullable: var_nullable,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  LanceError sse_decode_lance_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_message = sse_decode_String(deserializer);
    var var_code = sse_decode_String(deserializer);
    return LanceError(message: var_message, code: var_code);
  }

  @protected
  List<Map<String, ColumnValue>> sse_decode_list_Map_String_column_value_None(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Map<String, ColumnValue>>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_Map_String_column_value_None(deserializer));
    }
    return ans_;
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<FieldInfo> sse_decode_list_field_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FieldInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_field_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<double> sse_decode_list_prim_f_32_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  Float64List sse_decode_list_prim_f_64_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat64List(len_);
  }

  @protected
  Int64List sse_decode_list_prim_i_64_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getInt64List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<(String, ColumnValue)> sse_decode_list_record_string_column_value(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(String, ColumnValue)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_string_column_value(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_bool(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  QueryResult sse_decode_query_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_columns = sse_decode_list_String(deserializer);
    var var_rows = sse_decode_list_Map_String_column_value_None(deserializer);
    var var_numRows = sse_decode_usize(deserializer);
    return QueryResult(
      columns: var_columns,
      rows: var_rows,
      numRows: var_numRows,
    );
  }

  @protected
  (String, ColumnValue) sse_decode_record_string_column_value(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_column_value(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  SchemaInfo sse_decode_schema_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_fields = sse_decode_list_field_info(deserializer);
    return SchemaInfo(fields: var_fields);
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceConnection(
    LanceConnection self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as LanceConnectionImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceTable(
    LanceTable self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as LanceTableImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceVectorQuery(
    LanceVectorQuery self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as LanceVectorQueryImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceConnection(
    LanceConnection self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as LanceConnectionImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceTable(
    LanceTable self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as LanceTableImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceVectorQuery(
    LanceVectorQuery self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as LanceVectorQueryImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void sse_encode_Map_String_column_value_None(
    Map<String, ColumnValue> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_record_string_column_value(
      self.entries.map((e) => (e.key, e.value)).toList(),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceConnection(
    LanceConnection self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as LanceConnectionImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceTable(
    LanceTable self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as LanceTableImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanceVectorQuery(
    LanceVectorQuery self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as LanceVectorQueryImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_column_value(ColumnValue self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case ColumnValue_Null():
        sse_encode_i_32(0, serializer);
      case ColumnValue_Bool(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_bool(field0, serializer);
      case ColumnValue_Int(field0: final field0):
        sse_encode_i_32(2, serializer);
        sse_encode_i_64(field0, serializer);
      case ColumnValue_Float(field0: final field0):
        sse_encode_i_32(3, serializer);
        sse_encode_f_64(field0, serializer);
      case ColumnValue_String(field0: final field0):
        sse_encode_i_32(4, serializer);
        sse_encode_String(field0, serializer);
      case ColumnValue_FloatArray(field0: final field0):
        sse_encode_i_32(5, serializer);
        sse_encode_list_prim_f_64_strict(field0, serializer);
      case ColumnValue_IntArray(field0: final field0):
        sse_encode_i_32(6, serializer);
        sse_encode_list_prim_i_64_strict(field0, serializer);
      case ColumnValue_StringArray(field0: final field0):
        sse_encode_i_32(7, serializer);
        sse_encode_list_String(field0, serializer);
    }
  }

  @protected
  void sse_encode_distance_type(DistanceType self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_field_info(FieldInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.dataType, serializer);
    sse_encode_bool(self.nullable, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_lance_error(LanceError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
    sse_encode_String(self.code, serializer);
  }

  @protected
  void sse_encode_list_Map_String_column_value_None(
    List<Map<String, ColumnValue>> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_Map_String_column_value_None(item, serializer);
    }
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_field_info(
    List<FieldInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_field_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_f_32_loose(
    List<double> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(
      self is Float32List ? self : Float32List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(self);
  }

  @protected
  void sse_encode_list_prim_f_64_strict(
    Float64List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat64List(self);
  }

  @protected
  void sse_encode_list_prim_i_64_strict(
    Int64List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putInt64List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_record_string_column_value(
    List<(String, ColumnValue)> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_string_column_value(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_bool(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_String(
    List<String>? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_String(self, serializer);
    }
  }

  @protected
  void sse_encode_query_result(QueryResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_String(self.columns, serializer);
    sse_encode_list_Map_String_column_value_None(self.rows, serializer);
    sse_encode_usize(self.numRows, serializer);
  }

  @protected
  void sse_encode_record_string_column_value(
    (String, ColumnValue) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_column_value(self.$2, serializer);
  }

  @protected
  void sse_encode_schema_info(SchemaInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_field_info(self.fields, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class LanceConnectionImpl extends RustOpaque implements LanceConnection {
  // Not to be used by end users
  LanceConnectionImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  LanceConnectionImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_LanceConnection,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_LanceConnection,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_LanceConnectionPtr,
  );

  /// Create a new empty table with the given schema
  ///
  /// # Arguments
  /// * `name` - Name of the table to create
  /// * `schema_json` - JSON representation of the schema
  ///
  /// Schema JSON format:
  /// ```json
  /// {
  ///   "fields": [
  ///     {"name": "id", "type": "int64", "nullable": false},
  ///     {"name": "text", "type": "string", "nullable": true},
  ///     {"name": "vector", "type": "fixed_size_list", "list_size": 128, "item_type": "float32", "nullable": false}
  ///   ]
  /// }
  /// ```
  Future<LanceTable> createEmptyTable({
    required String name,
    required String schemaJson,
  }) => RustLib.instance.api.crateApiConnectionLanceConnectionCreateEmptyTable(
    that: this,
    name: name,
    schemaJson: schemaJson,
  );

  /// Create a new table with initial data
  ///
  /// # Arguments
  /// * `name` - Name of the table to create
  /// * `data_json` - JSON array of row objects
  ///
  /// Data JSON format:
  /// ```json
  /// [
  ///   {"id": 1, "text": "hello", "vector": [0.1, 0.2, ...]},
  ///   {"id": 2, "text": "world", "vector": [0.3, 0.4, ...]}
  /// ]
  /// ```
  Future<LanceTable> createTable({
    required String name,
    required String dataJson,
  }) => RustLib.instance.api.crateApiConnectionLanceConnectionCreateTable(
    that: this,
    name: name,
    dataJson: dataJson,
  );

  /// Drop (delete) a table from the database
  Future<void> dropTable({required String name}) => RustLib.instance.api
      .crateApiConnectionLanceConnectionDropTable(that: this, name: name);

  /// Open an existing table by name
  Future<LanceTable> openTable({required String name}) => RustLib.instance.api
      .crateApiConnectionLanceConnectionOpenTable(that: this, name: name);

  /// List all table names in the database
  Future<List<String>> tableNames() => RustLib.instance.api
      .crateApiConnectionLanceConnectionTableNames(that: this);
}

@sealed
class LanceTableImpl extends RustOpaque implements LanceTable {
  // Not to be used by end users
  LanceTableImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  LanceTableImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_LanceTable,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_LanceTable,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_LanceTablePtr,
  );

  /// Add data to the table
  ///
  /// # Arguments
  /// * `data_json` - JSON array of row objects
  ///
  /// Data JSON format:
  /// ```json
  /// [
  ///   {"id": 1, "text": "hello", "vector": [0.1, 0.2, ...]},
  ///   {"id": 2, "text": "world", "vector": [0.3, 0.4, ...]}
  /// ]
  /// ```
  Future<void> add({required String dataJson}) => RustLib.instance.api
      .crateApiTableLanceTableAdd(that: this, dataJson: dataJson);

  /// Count the number of rows in the table
  Future<PlatformInt64> countRows({String? filter}) => RustLib.instance.api
      .crateApiTableLanceTableCountRows(that: this, filter: filter);

  /// Create an index on the table
  ///
  /// # Arguments
  /// * `column` - Column name to create index on
  /// * `index_type` - Type of index (e.g., "ivf_pq", "btree", "auto")
  /// * `replace` - Whether to replace existing index
  Future<void> createIndex({
    required String column,
    String? indexType,
    bool? replace,
  }) => RustLib.instance.api.crateApiTableLanceTableCreateIndex(
    that: this,
    column: column,
    indexType: indexType,
    replace: replace,
  );

  /// Delete rows matching the predicate
  ///
  /// # Arguments
  /// * `predicate` - SQL WHERE clause predicate (e.g., "id > 10")
  Future<void> delete({required String predicate}) => RustLib.instance.api
      .crateApiTableLanceTableDelete(that: this, predicate: predicate);

  /// List all indexes on the table
  Future<List<String>> listIndices() =>
      RustLib.instance.api.crateApiTableLanceTableListIndices(that: this);

  /// Get the table name
  String name() => RustLib.instance.api.crateApiTableLanceTableName(that: this);

  /// Optimize the table (compact files, etc.)
  Future<String> optimize() =>
      RustLib.instance.api.crateApiTableLanceTableOptimize(that: this);

  /// Execute a simple query and return all results
  ///
  /// # Arguments
  /// * `columns` - Optional list of columns to select (None = all columns)
  /// * `filter` - Optional SQL WHERE clause predicate
  /// * `limit` - Optional maximum number of rows to return
  Future<QueryResult> query({
    List<String>? columns,
    String? filter,
    PlatformInt64? limit,
  }) => RustLib.instance.api.crateApiTableLanceTableQuery(
    that: this,
    columns: columns,
    filter: filter,
    limit: limit,
  );

  /// Get the table schema
  Future<SchemaInfo> schema() =>
      RustLib.instance.api.crateApiTableLanceTableSchema(that: this);

  /// Update rows matching the predicate
  ///
  /// # Arguments
  /// * `updates_json` - JSON object with column names and new values
  /// * `predicate` - Optional SQL WHERE clause predicate
  ///
  /// Updates JSON format:
  /// ```json
  /// {"column1": "new_value", "column2": 123}
  /// ```
  Future<PlatformInt64> update({
    required String updatesJson,
    String? predicate,
  }) => RustLib.instance.api.crateApiTableLanceTableUpdate(
    that: this,
    updatesJson: updatesJson,
    predicate: predicate,
  );

  /// Perform a vector similarity search
  ///
  /// # Arguments
  /// * `vector` - Query vector as a list of floats
  /// * `column` - Optional name of the vector column (default: auto-detect)
  ///
  /// Returns a VectorQuery builder for further configuration
  Future<LanceVectorQuery> vectorSearch({
    required List<double> vector,
    String? column,
  }) => RustLib.instance.api.crateApiTableLanceTableVectorSearch(
    that: this,
    vector: vector,
    column: column,
  );

  /// Get the current version of the table
  Future<PlatformInt64> version() =>
      RustLib.instance.api.crateApiTableLanceTableVersion(that: this);
}

@sealed
class LanceVectorQueryImpl extends RustOpaque implements LanceVectorQuery {
  // Not to be used by end users
  LanceVectorQueryImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  LanceVectorQueryImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_LanceVectorQuery,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_LanceVectorQuery,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_LanceVectorQueryPtr,
  );

  /// Set the vector column name for the search
  LanceVectorQuery column({required String column}) => RustLib.instance.api
      .crateApiQueryLanceVectorQueryColumn(that: this, column: column);

  /// Set the distance metric type
  LanceVectorQuery distanceType({required DistanceType distanceType}) =>
      RustLib.instance.api.crateApiQueryLanceVectorQueryDistanceType(
        that: this,
        distanceType: distanceType,
      );

  /// Execute the vector search and return results
  Future<QueryResult> execute() =>
      RustLib.instance.api.crateApiQueryLanceVectorQueryExecute(that: this);

  /// Set the maximum number of results to return
  LanceVectorQuery limit({required PlatformInt64 limit}) => RustLib.instance.api
      .crateApiQueryLanceVectorQueryLimit(that: this, limit: limit);

  /// Set the number of probes for IVF index (higher = more accurate, slower)
  LanceVectorQuery nprobes({required int nprobes}) => RustLib.instance.api
      .crateApiQueryLanceVectorQueryNprobes(that: this, nprobes: nprobes);

  /// Set the offset for pagination
  LanceVectorQuery offset({required PlatformInt64 offset}) => RustLib
      .instance
      .api
      .crateApiQueryLanceVectorQueryOffset(that: this, offset: offset);

  /// Add a filter predicate (SQL WHERE clause)
  LanceVectorQuery onlyIf({required String predicate}) => RustLib.instance.api
      .crateApiQueryLanceVectorQueryOnlyIf(that: this, predicate: predicate);

  /// Enable post-filtering (filter after vector search instead of before)
  LanceVectorQuery postfilter() =>
      RustLib.instance.api.crateApiQueryLanceVectorQueryPostfilter(that: this);

  /// Set the refinement factor for more accurate results
  LanceVectorQuery refineFactor({required int factor}) => RustLib.instance.api
      .crateApiQueryLanceVectorQueryRefineFactor(that: this, factor: factor);

  /// Select specific columns to return
  LanceVectorQuery select({required List<String> columns}) => RustLib
      .instance
      .api
      .crateApiQueryLanceVectorQuerySelect(that: this, columns: columns);
}
