// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'table.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `infer_data_type`, `inner`, `json_to_record_batches`, `parse_schema_json`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `new`

/// Connect to a LanceDB database at the given URI
///
/// # Arguments
/// * `uri` - Path to the database directory (local) or cloud URI
///
/// # Example
/// ```dart
/// final db = await connect("/path/to/db");
/// final db = await connect("s3://bucket/path");
/// ```
Future<LanceConnection> connect({required String uri}) =>
    RustLib.instance.api.crateApiConnectionConnect(uri: uri);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LanceConnection>>
abstract class LanceConnection implements RustOpaqueInterface {
  /// Create a new empty table with the given schema
  ///
  /// # Arguments
  /// * `name` - Name of the table to create
  /// * `schema_json` - JSON representation of the schema
  ///
  /// Schema JSON format:
  /// ```json
  /// {
  ///   "fields": [
  ///     {"name": "id", "type": "int64", "nullable": false},
  ///     {"name": "text", "type": "string", "nullable": true},
  ///     {"name": "vector", "type": "fixed_size_list", "list_size": 128, "item_type": "float32", "nullable": false}
  ///   ]
  /// }
  /// ```
  Future<LanceTable> createEmptyTable({
    required String name,
    required String schemaJson,
  });

  /// Create a new table with initial data
  ///
  /// # Arguments
  /// * `name` - Name of the table to create
  /// * `data_json` - JSON array of row objects
  ///
  /// Data JSON format:
  /// ```json
  /// [
  ///   {"id": 1, "text": "hello", "vector": [0.1, 0.2, ...]},
  ///   {"id": 2, "text": "world", "vector": [0.3, 0.4, ...]}
  /// ]
  /// ```
  Future<LanceTable> createTable({
    required String name,
    required String dataJson,
  });

  /// Drop (delete) a table from the database
  Future<void> dropTable({required String name});

  /// Open an existing table by name
  Future<LanceTable> openTable({required String name});

  /// List all table names in the database
  Future<List<String>> tableNames();
}
