// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `with_column`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `new`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LanceVectorQuery>>
abstract class LanceVectorQuery implements RustOpaqueInterface {
  /// Set the vector column name for the search
  LanceVectorQuery column({required String column});

  /// Set the distance metric type
  LanceVectorQuery distanceType({required DistanceType distanceType});

  /// Execute the vector search and return results
  Future<QueryResult> execute();

  /// Set the maximum number of results to return
  LanceVectorQuery limit({required PlatformInt64 limit});

  /// Set the number of probes for IVF index (higher = more accurate, slower)
  LanceVectorQuery nprobes({required int nprobes});

  /// Set the offset for pagination
  LanceVectorQuery offset({required PlatformInt64 offset});

  /// Add a filter predicate (SQL WHERE clause)
  LanceVectorQuery onlyIf({required String predicate});

  /// Enable post-filtering (filter after vector search instead of before)
  LanceVectorQuery postfilter();

  /// Set the refinement factor for more accurate results
  LanceVectorQuery refineFactor({required int factor});

  /// Select specific columns to return
  LanceVectorQuery select({required List<String> columns});
}
