// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'query.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `extract_value`, `infer_data_type`, `inner`, `json_to_record_batches`, `record_batches_to_query_result`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `new`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LanceTable>>
abstract class LanceTable implements RustOpaqueInterface {
  /// Add data to the table
  ///
  /// # Arguments
  /// * `data_json` - JSON array of row objects
  ///
  /// Data JSON format:
  /// ```json
  /// [
  ///   {"id": 1, "text": "hello", "vector": [0.1, 0.2, ...]},
  ///   {"id": 2, "text": "world", "vector": [0.3, 0.4, ...]}
  /// ]
  /// ```
  Future<void> add({required String dataJson});

  /// Count the number of rows in the table
  Future<PlatformInt64> countRows({String? filter});

  /// Create an index on the table
  ///
  /// # Arguments
  /// * `column` - Column name to create index on
  /// * `index_type` - Type of index (e.g., "ivf_pq", "btree", "auto")
  /// * `replace` - Whether to replace existing index
  Future<void> createIndex({
    required String column,
    String? indexType,
    bool? replace,
  });

  /// Delete rows matching the predicate
  ///
  /// # Arguments
  /// * `predicate` - SQL WHERE clause predicate (e.g., "id > 10")
  Future<void> delete({required String predicate});

  /// List all indexes on the table
  Future<List<String>> listIndices();

  /// Get the table name
  String name();

  /// Optimize the table (compact files, etc.)
  Future<String> optimize();

  /// Execute a simple query and return all results
  ///
  /// # Arguments
  /// * `columns` - Optional list of columns to select (None = all columns)
  /// * `filter` - Optional SQL WHERE clause predicate
  /// * `limit` - Optional maximum number of rows to return
  Future<QueryResult> query({
    List<String>? columns,
    String? filter,
    PlatformInt64? limit,
  });

  /// Get the table schema
  Future<SchemaInfo> schema();

  /// Update rows matching the predicate
  ///
  /// # Arguments
  /// * `updates_json` - JSON object with column names and new values
  /// * `predicate` - Optional SQL WHERE clause predicate
  ///
  /// Updates JSON format:
  /// ```json
  /// {"column1": "new_value", "column2": 123}
  /// ```
  Future<PlatformInt64> update({
    required String updatesJson,
    String? predicate,
  });

  /// Perform a vector similarity search
  ///
  /// # Arguments
  /// * `vector` - Query vector as a list of floats
  /// * `column` - Optional name of the vector column (default: auto-detect)
  ///
  /// Returns a VectorQuery builder for further configuration
  Future<LanceVectorQuery> vectorSearch({
    required List<double> vector,
    String? column,
  });

  /// Get the current version of the table
  Future<PlatformInt64> version();
}
