// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'types.freezed.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `IndexType`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`

@freezed
sealed class ColumnValue with _$ColumnValue {
  const ColumnValue._();

  const factory ColumnValue.null_() = ColumnValue_Null;
  const factory ColumnValue.bool(bool field0) = ColumnValue_Bool;
  const factory ColumnValue.int(PlatformInt64 field0) = ColumnValue_Int;
  const factory ColumnValue.float(double field0) = ColumnValue_Float;
  const factory ColumnValue.string(String field0) = ColumnValue_String;
  const factory ColumnValue.floatArray(Float64List field0) =
      ColumnValue_FloatArray;
  const factory ColumnValue.intArray(Int64List field0) = ColumnValue_IntArray;
  const factory ColumnValue.stringArray(List<String> field0) =
      ColumnValue_StringArray;
}

/// Distance metric for vector search
enum DistanceType {
  /// Euclidean distance (L2)
  l2,

  /// Cosine similarity
  cosine,

  /// Dot product
  dot,
}

/// Schema field information
class FieldInfo {
  final String name;
  final String dataType;
  final bool nullable;

  const FieldInfo({
    required this.name,
    required this.dataType,
    required this.nullable,
  });

  @override
  int get hashCode => name.hashCode ^ dataType.hashCode ^ nullable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FieldInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          dataType == other.dataType &&
          nullable == other.nullable;
}

/// Error type for LanceDB operations
class LanceError implements FrbException {
  final String message;
  final String code;

  const LanceError({required this.message, required this.code});

  @override
  int get hashCode => message.hashCode ^ code.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LanceError &&
          runtimeType == other.runtimeType &&
          message == other.message &&
          code == other.code;
}

/// Query result containing rows of data
class QueryResult {
  final List<String> columns;
  final List<Map<String, ColumnValue>> rows;
  final BigInt numRows;

  const QueryResult({
    required this.columns,
    required this.rows,
    required this.numRows,
  });

  static Future<QueryResult> empty() =>
      RustLib.instance.api.crateApiTypesQueryResultEmpty();

  @override
  int get hashCode => columns.hashCode ^ rows.hashCode ^ numRows.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QueryResult &&
          runtimeType == other.runtimeType &&
          columns == other.columns &&
          rows == other.rows &&
          numRows == other.numRows;
}

/// Table schema information
class SchemaInfo {
  final List<FieldInfo> fields;

  const SchemaInfo({required this.fields});

  @override
  int get hashCode => fields.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SchemaInfo &&
          runtimeType == other.runtimeType &&
          fields == other.fields;
}
